sonar.projectKey=GHA-CICD
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,build/**,.next/**,coverage/**,k3s/**,**/*.min.js
sonar.javascript.node.maxspace=4096
sonar.javascript.enabled=false

